package informationDAO;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;

import user.User;

/**
 * It defines necessary functions for userDAO.
 * @author Jaemin Oh
 *
 */
public interface UserDAO {
	
	/**
	 * Create user object generated by user
	 * @param licenseNumber: A valid driver's license number.
	 * @return: A user object.
	 * @throws FileNotFoundException: Thrown if connection to user database is not successful.
	 * @throws ParseException: Thrown if parsing date is not sucessful.
	 */
	public User createUser(String licenseNumber) throws FileNotFoundException, ParseException;
	
	/**
	 * Add user into user database.
	 * @param user: A user object created by createUser
	 * @return: True if user is successfully enrolled, if not, get False.
	 * @throws FileNotFoundException: Thrown if connection to user database is not successful.
	 */
	public boolean addUser(User user) throws FileNotFoundException;
	
	/**
	 * Delete user from user database.
	 * @param licenseNumber: A valid driver's license number to delete user information.
	 * @return: True if user is successfully deleted, if not, get False.
	 * @throws IOException: Thrown if connection to user database is not successful.
	 */
	public boolean deleteUser(String licenseNumber) throws IOException;
}
